version: '3.3'

services:
  jemsao-fe-prod:
    container_name: jemsao-fe-prod
    image: registry.jems-group.com/jemsao/jemsao-frontend:production
    ports:
      - '5025:80'
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    command: ['nginx', '-g', 'daemon off;']
